name: telemetry-infra
services:
  telemetry-db:
    image: 'timescale/timescaledb:latest-pg18'
    container_name: telemetry-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=telemetry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d telemetry' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - telemetry-db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M

  telemetry-kafka-broker:
    image: 'confluentinc/cp-kafka:7.8.0'
    container_name: telemetry-kafka-broker
    restart: unless-stopped
    environment:
      # KRaft mode configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@telemetry-kafka-broker:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Listener configuration
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://telemetry-kafka-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # Cluster and log configuration
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # Performance tuning
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    ports:
      - '29092:29092'
      - '9093:9093'
    healthcheck:
      test: [ 'CMD-SHELL', 'kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1' ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - telemetry-kafka-broker-data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          memory: 1G


volumes:
  telemetry-db-data:
  telemetry-kafka-broker-data:
